[firebase]
type = "service_account"
project_id = "towel-website"
private_key_id = "2555a650ddc61a03754df0c44125b827fc7520aa"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDDskusoByF7VKR
BP+3FCNv/TnLBkzOPBo80HNQiRnYbytL8+dSLcYFfCfw7apVSshunVjOYKCyrKyN
B37R82VGIA/ruFlQnAKhLDZMoevvTeXxkjcUB3iWtOgEOsVys1dAlLQsPE+w+lQZ
jacskuWuiHCD5xJ3F6spjm70QA4lk32YAEl5rDOlJ66HXoFabuSNFR5tp41N0JV9
ayUZzdzpXqTe1BM3AZLIzujT/X6wXX1Euk1qTjNJm+x7d4HQ5OvduZICChRIGYLG
NeZzuyojqPlIPaSE2PUo+XpqbUVbrfhL+7kx0MKx64vSx3ctR8RiwGi+7naONWr2
9lwa+cR9AgMBAAECggEAVpHnjxBvPcG8DkIfWx5yBMcJC2qYjH0jADcYZA6aW9fl
194oPP7ZxDBlvNtuR/fijahWkklFnXTsiiDANeFNskVZtaWiARpawXC8/o58wCp+
J6zOZ7JcYpLZtpFHKlPyq7N8trrhaAF9Naanxvye1WQvHfKZBQz331TOeYdimrUL
sWhipYP7qRw3tcvldC36bB/0lls1rg7OxzadYNLJ+fad57zmqLSwKLfH5V9YXJ58
KXKpGyA/wsH2NkCS/C2nq6VUQd68i/cfC1TSfDxsWvFFx7GeRF3Z2/MeC4BEHzPY
TIZhM+33a50WD/xVZpkdh2U+RfG23ulCgWdeHcVVgwKBgQDmvdfNnKkNEa7L++Hl
RuvOdOtdK2lUBXjD9v17cBtFGregt/Ru2wgV05IjM7VnLxT2opcn19VOj405UnRk
HYcAdHd+A8GqruWzRYHzfkKqNz3hLtQuyeEKXZGWCQytUEMr3rBNUMJWuw04L1MC
HbQ4M0Gec2ul0FFN/ykmpChPfwKBgQDZHl7cDSGWNNBWDoIImlGKD2Z14tSVag1m
MbQrvsGQ+rJNZkD+4F8Cg+KNlqVQduDYDFN8sUpzwOPXxcs26blkhxB62GxtVhQN
gRV0Fh7/ChqwY6BE5SvT6JOWmUdFtls9YRb4+mkirFU5NGl29t+xiFwYT/PjLZUx
t6osyYoqAwKBgQCkAGlDfkb1wAzCdYxQv0DZZGbpuPJLQvxcJNB0DPGFA4Fi3X0B
0fKEOPWUyar05RT8XAId0p2NEiEpjf6mLgqHe0B3M8pSO6+N5SiBXcuaWltEE1nC
y8CE8o6I2nPFN9gWdVhQC8elh5vUxGY2idBPZbcNHTJ1D4TKcELacTEplwKBgQCD
UUEiarbDuJHBWuj+9wcWL5ZS+qyE6i3Mf4dvZeKBI3+wHIZ3IZGVXdsqs9CsyBnZ
0iq0oi5bsHCd0r3EKry8towbIMcDoipiuI4XNkHtE1ltEfSfdtR5SJPrZC2dVlv8
1bolQJ9SH1U0UiTvlQVaxRSeh80EvE8eUO2WRRdRrQKBgQCfGfsk7n2xgDbM5MLo
tlCBlO10NOYsvDUzDvsC7n8xZC0ZGz5ooVp0LanhMxvay55LPl96a42H3RuVMoUq
RIBOYUyljVrkjr3nyQGpIuiXWvPWq4LKCze25iAcepeWHGwrMESmNtZwQpFIM/ri
kr06RKZquQ4WOfMSdziv7LLMlw==
-----END PRIVATE KEY-----
"""
client_email = "firebase-adminsdk-fbsvc@towel-website.iam.gserviceaccount.com"
client_id = "104672141125928127740"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40towel-website.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
